### ISSUE TITLE
Ability to test version output in isolation

### ISSUE THREAD

**Issue by kdabir** [kdabir/has#21]
If we change the current regex, we are not sure if existing commands' version can still be extracted. we can't run all commands in CI because they might not be present on CI servers in the first place.

To solve this, the code needs to be organized such that the version extraction is decoupled from the command execution part. 

1. Execute the command and capture the output (both out & err), and exit status
2. Compare the exit status against valid status (mostly 0 but can be different for some commands)
3. Pass the output for some default version extraction strategies, or custom ones if command needs one
4. These strategies must be functions that can be unit tested in bats file against actual output of commands.

**Comment by sdolenc** [comment]
Regarding
> we can't run all commands in CI because they might not be present on CI servers in the first place.

Some continuous integration solutions allow you to run tests on any container image you want. We could use existing (or create) container images with the packages that tests are expecting.

Let me know if that would be helpful. I'd be happy to discuss this further and/or put together a proof-of-concept.

**Comment by kdabir** [comment]
Sure that would be a great option. We can try it on Github Actions as well now. I am happy to merge PRs

**Comment by sdolenc** [comment]
Awesome! My initial thinking is to cover a couple versions of each package. That way we could ensure the version command/regex we are using works for multiple releases.

If that sounds okay then do we want to test packages released in the previous
- 5 years or
- 10 years

Testing both releases time-frames should be about the same amount of work, but I would prefer to use
- GitHub Actions if I'm testing software released 2015+ and
- CircleCI if I'm testing software released 2010+

I want to use a package manager like apt-get while creating the new containers instead of compiling a particular version of a package myself. I found running old releases of Debian/Ubuntu goes smoother on CircleCI than on GitHub Actions (due to a node requirement on GitHub Actions).

**Comment by kdabir** [comment]
This sounds like good idea. I have a suggestion to make though. People are hardly using 10+ years older packages now for development tools. So even if regex breaks, we needn't worry so much. It may be a better strategy to test for last two major versions rather than focusing on number of years. What do you think?

**Comment by sdolenc** [comment]
Sounds great to me! I'll start experimenting and drafting the test feature. I'll use existing or create new public containers on Docker Hub and use GitHub Actions for continuous integration.

I'll ping this thread when I encounter other design decisions :)

**Comment by kdabir** [comment]
Thank you so much for volunteering on this. Much appreciated.

**Comment by sdolenc** [comment]
https://github.com/kdabir/has/pull/43 is ready for review :)
